version: '3.7'

services:
  frontend:
    container_name: therapease_frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./client:/code/app
    env_file:
      - ./.env.sample
    ports:
      - "9002:3000"
      - "24600:24600"
    depends_on:
      - api
  api:
    container_name: therapease_api
    build:
      context: ./api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/usr/src/app
    ports:
      - "9001:8000"
    env_file:
      - ./.env.sample
  db: 
    container_name: therapease_db
    image: postgres:15.4-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.sample
  cache:
    container_name: therapease_cache
    image: redis:6.0.20-alpine3.18
  storage:
    image: docker.io/bitnami/minio:2023
    env_file:
      - ./.env.sample
    ports:
      - '9000:9000'
      - '9003:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'  
  # geocoding:
  #   container_name: therapease_geocoding
  #   image: mediagis/nominatim:4.2
  #   volumes:
  #     - geocoding_data:/var/lib/postgresql/14/main
  #   shm_size: '1gb'
  #   env_file:
  #     - ./.env.sample

volumes:
  # geocoding_data:
  postgres_data:
  minio_data:
    driver: local