version: '3.7'

services:
  frontend:
    container_name: therapease_frontend
    image: ghcr.io/ausome-maps/therapease-ui:latest
    command: node server/index.mjs
    env_file:
      - ./.env.sample
    ports:
      - "9002:9002"
    depends_on:
      - api
  api:
    container_name: therapease_api
    image: ghcr.io/ausome-maps/therapease-api:latest
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    expose:
      - 5000
    env_file:
      - ./.env.sample
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`subdomain.example.com`)" # need to be configured in DNS registrar
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
    depends_on:
      - geocoding
      - search
      - cache
  cache:
    container_name: therapease_cache
    image: redis:6.0.20-alpine3.18
  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/infrastructure/traefik/traefik.prod.toml:/etc/traefik/traefik.toml"
  geocoding:
    container_name: therapease_geocoding
    image: mediagis/nominatim:4.2
    volumes:
      - geocoding_data:/var/lib/postgresql/14/main
    shm_size: '1gb'
    env_file:
      - ./.env.sample
  search:
    container_name: therapease_search
    image: opensearchproject/opensearch:2.9.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=therapease_search # Name the node that will run in this container
      - discovery.seed_hosts=therapease_search
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - DISABLE_SECURITY_PLUGIN=true # this should be removed if SSL is configured
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes: 
      - search_data:/usr/share/opensearch/data

volumes:
  geocoding_data:
  search_data: 