version: '3.7'

services:
  gateway:
    container_name: therapease_gateway
    image: therapease_gateway
    build:
      context: ./api/gateway
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - "9001:80"
    env_file:
      - ./.env.sample
    depends_on:
      - geocoding
  geocoding:
    container_name: therapease_geocoding
    image: mediagis/nominatim:4.2
    volumes:
      - geocoding_data:/var/lib/postgresql/14/main
    shm_size: '1gb'
    env_file:
      - ./.env.sample
  search:
    container_name: therapease_search
    image: opensearchproject/opensearch:2.9.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=therapease_search # Name the node that will run in this container
      - discovery.seed_hosts=therapease_search
      - cluster.initial_cluster_manager_nodes=therapease_search # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - DISABLE_SECURITY_PLUGIN=true # this should be removed if SSL is configured
      # - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes: 
      - search_data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

volumes:
  geocoding_data:
  search_data: 