version: '3.7'

services:
  geocoding:
    container_name: therapease_geocoding
    image: mediagis/nominatim:4.2
    ports:
      - "9000:8080"
    volumes:
      - ./django:/usr/src/app/
      - geocoding_data:/var/lib/postgresql/data/
    shm_size: '1gb'
    env_file:
      - ./.env.sample

volumes:
  geocoding_data: