# Generated by Django 4.2.7 on 2023-11-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityproperties',
            old_name='id',
            new_name='osm_id',
        ),
    ]
