# Generated by Django 4.2.7 on 2023-11-14 23:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_rename_id_facilityproperties_osm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityproperties',
            name='caters_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
