# Generated by Django 4.2.7 on 2023-12-07 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0004_alter_facilityproperties_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facilityproperties",
            options={
                "ordering": ["-osm_id"],
                "verbose_name": "Facility Properties",
                "verbose_name_plural": "Facility Properties",
            },
        ),
    ]
