# Generated by Django 4.2.7 on 2023-12-16 00:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0008_alter_facilityproperties_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facilityproperties",
            old_name="images",
            new_name="old_images",
        ),
    ]
