all:
  hosts: <ip-address>
  vars:
    ansible_port: 22
    ansible_user: therapease
    ansible_python_interpreter: /usr/bin/python3
    app_version: 1.0.0
    app_user: therapease
    username: therapease
    cr:
      user: <github-username>
      password: <github-pat>

    apps_directory: "/home/{{ ansible_user }}/apps"
    therapease_api_domain_name: "<api-domain-name>"
    therapease_ui_domain_name: "<ui-domain-name>"
    therapease_storage_domain_name: "<storage-domain-name>"
    therapease_api_storage_domain_name: "<api-storage-domain-name>"
    therapease_monitor_domain_name: "<monitor-password>"
    api_secret_key: "<api-secret-key>"
    feedback_url: "<feedback-url>"
    google_tag_manager: "<google-tag-manager>"
    is_ssl: false
    minio:
      root: <miniouser>
      password: <miniouserpassword>
    postgres:
      username: <dbuser>
      password: <dbpassword>
      host: therapease_db
      dbname: therapeasedb

    deploy_therapease: yes
