[entryPoints]
  [entryPoints.api]
    address = ":9001"
  [entryPoints.api.http]
    [entryPoints.api.http.redirections]
      [entryPoints.api.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.ui]
    address = ":9002"
  [entryPoints.ui.http]
    [entryPoints.api.http.redirections]
      [entryPoints.api.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
  email = "info@ausomemaps.org"
  storage= "acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"
