---
therapease_ui_domain_name: "sample.com"
therapease_api_domain_name: "api.sample.com"
therapease_storage_domain_name: "storage.sample.com"
therapease_api_storage_domain_name: "s3.sample.com"
therapease_monitor_domain_name: "monitor.sample.com"
copyright_year: "2026"
is_ssl: false
geocode_url: "https://nominatim.openstreetmap.org/search"
feature_auth_enabled: 1
feature_registration_enabled: 0
feedback_url: "https://forms.gle/example"
google_tag_manager: ""
api_secret_key: "change-me"
postgres:
  username: tuser
  password: tpassword
  host: t_db_host
  dbname: tdb
minio:
  root: t_minio
  password: tpasswordminio

sendgrid_api_key: api_key
therapease_system_email: system@sample.com
therapease_admin_email: admin@sample.com