---

- hosts: all
  tasks:
    - name: stopping therapease
      become: yes
      community.docker.docker_compose_v2:
        project_src: "{{apps_directory}}"
        files: "docker-compose.therapease.yml"
        state: stopped
