---

- hosts: all
  tasks:
    - name: stopping therapease
      become: yes
      docker_compose:
        project_src: "{{apps_directory}}"
        files: "docker-compose.therapease.yml"
        state: present
        stopped: yes