# Generated by Django 4.2.7 on 2023-12-23 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_rename_role_roles_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roles",
            old_name="role_types",
            new_name="role_type",
        ),
    ]
