# Generated by Django 4.2.7 on 2023-12-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_roles_role_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='permission',
            new_name='permissions',
        ),
    ]
