# Generated by Django 4.2.7 on 2023-12-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_organizationrole_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrole',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
