# Generated by Django 4.2.7 on 2023-12-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_organizationrole_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="other_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
