[entryPoints]
  [entryPoints.web]
  address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.websecure]
  address = ":443"

[api]
  dashboard = true

[accessLog]

[providers.docker]
  watch = true
  network = "web"

[certificatesResolvers.lets-encrypt.acme]
  email = "info@ausomemaps.org"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.file]
  filename = "traefik_dynamic.toml"