name: Therapease CI
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      opensearch:
        image: opensearchproject/opensearch:2.9.0
        ports:
          - 9200:9200
        env: 
          cluster.name: opensearch-cluster
          DISABLE_SECURITY_PLUGIN: true # this should be removed if SSL is configured
          discovery.type: single-node          
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
    - name: Run Tests
      env:
        SEARCH_URL: http://localhost:9200
      run: |
        cd api/app
        pytest -s
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: api/  # Set the build context to the root of the repository
        push: true  # Push the built image to the registry
        tags: ghcr.io/ausome-maps/therapease-api:latest