name: Therapease Client CI
on: push

jobs:
  test_build_push:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      if: github.ref == 'refs/heads/main'
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      if: github.ref == 'refs/heads/main'
      with:
        context: client/  # Set the build context to the root of the repository
        file: client/Dockerfile.prod
        push: true  # Push the built image to the registry
        tags: ghcr.io/ausome-maps/therapease-ui:latest
